name: .NET

on: 
    push:
        tags:
        - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build Mapper
      run: dotnet build -p:PackageVersion=${{steps.tag.outputs.tag}} --configuration Release ./src/GeneratedMapper/GeneratedMapper.csproj
    - name: Publish Mapper
      run: dotnet nuget push ./src/GeneratedMapper/bin/Release/*.nupkg -k ${{ secrets.NUGET_APIKEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate